##### 创建ndarray

In [1]:
data1 = [6, 7.5, 8, 0, 1]

In [3]:
import numpy as np
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
arr1.dtype

dtype('float64')

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.empty((2,3,2))

array([[[1.09488256e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.24610383e-306, 5.35079518e-038]],

       [[7.79715993e-043, 8.23591484e-067],
        [1.56143940e+161, 5.15627648e-062],
        [5.40127999e-062, 1.73196916e+185]]])

In [9]:
np.arrange(15)

AttributeError: module 'numpy' has no attribute 'arrange'